apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: storage-infra-appset
spec:
  generators:
    # Generator for apps that should deploy to all clusters.
    - matrix:
        generators:
          - clusters: {}
          - list:
              elements:
                # - appName: ceph-sci
                #   namespace: ceph-csi-rbd
                #   path: kubernetes/apps/ceph/ceph-csi/charts/ceph-csi-rbd
                #   type: helm
                - appName: openebs
                  namespace: openebs
                  path: kubernetes/apps/openebs
                  type: helm

  template:
    metadata:
      name: "{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: kube-infra-stack
      source:
        repoURL: git@github.com:raphaelmulenda/kube-infra-stack.git
        targetRevision: HEAD
        path: "{{path}}"
        helm:
          releaseName: "{{appName}}"
          valueFiles:
            - kubernetes/apps/openebs/values.yaml
      destination:
        name: "{{name}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
