apiVersion: v2
name: kube-infra-stack
description: A Helm chart to manage ArgoCD applications for kube-infra-stack
version: 0.1.0
appVersion: 1.0.0
type: application
dependencies:
  - name: argocd-apps
    version: 2.0.2
    repository: https://argoproj.github.io/argo-helm
