argocd-apps:
  projects:
    kube-infra-stack:
      namespace: argocd
      sourceRepos:
        - '*'
      destinations:
        - namespace: '*'
          server: https://kubernetes.default.svc
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      orphanedResources:
        warn: false

  applications:
    kube-infra-stack-root-app:
      namespace: argocd
      project: kube-infra-stack
      source:
        repoURL: git@github.com:raphaelmulenda/kube-infra-stack.git
        targetRevision: HEAD
        path: kubernetes/argocd-mngr-app/
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
